[package]
name = "portal-cli"
version = "0.1.0"
description = "Portal-tunnel client CLI."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "portal"
path = "src/main.rs"

[dependencies]
portal-sdk = { workspace = true }

clap = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[lints]
workspace = true
