[package]
name = "e2e"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
portal-relay = { workspace = true }
portal-crypto = { workspace = true, features = ["insecure-test-constructors"] }
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true }

[lints]
workspace = true
